# Generated by Django 4.2.19 on 2025-03-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
