# Generated by Django 4.2 on 2025-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=20)),
                ('camp_name', models.CharField(max_length=200)),
                ('description_camp', models.TextField()),
                ('upload_file', models.FileField(upload_to='camp_uploads/')),
                ('typeof_camp', models.CharField(choices=[('health', 'ค่ายสายสุขภาพ'), ('engineer', 'ค่ายสายวิศวกรรม'), ('language', 'ค่ายสายภาษา'), ('architecture', 'ค่ายสายสถาปัตย์'), ('volunteer', 'ค่ายอาสา'), ('digital_it', 'ค่ายสายดิจิทัล/IT'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทค่าย')),
                ('start_date', models.DateField()),
                ('final_date', models.DateField()),
                ('due_date', models.DateField()),
                ('num_candi', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('none', 'ไม่มีค่าใช้จ่าย'), ('pre', 'จ่ายตอนสมัคร'), ('post', 'จ่ายหลังประกาศรายชื่อ')], max_length=10, verbose_name='วิธีการชำระ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('candi_proper', models.TextField(blank=True, null=True)),
                ('activity_mode', models.CharField(choices=[('online', 'กิจกรรมออนไลน์'), ('onsite', 'กิจกรรมออนไซต์')], max_length=10)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('ig', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkcamp', models.URLField()),
                ('organize_camp', models.CharField(max_length=200)),
                ('has_organized', models.BooleanField(help_text='ติ๊กถ้าคุณเคยจัดค่ายนี้', null=True, verbose_name='เคยจัดไหม')),
                ('detail_activity', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='camp_posters/')),
                ('prove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('hobby', models.TextField()),
                ('interest', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
