# Generated by Django 4.2 on 2025-05-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='candi_proper',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.AddField(
            model_name='camp',
            name='age_condition',
            field=models.CharField(blank=True, choices=[('no_limit', 'ไม่กำหนด'), ('from', 'ตั้งแต่')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='degree_condition',
            field=models.CharField(blank=True, choices=[('all', 'ทั้งหมด'), ('from', 'ตั้งแต่')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='degree_from',
            field=models.CharField(blank=True, choices=[('bachelor', 'ตรี'), ('master', 'โท'), ('doctorate', 'เอก')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='degree_to',
            field=models.CharField(blank=True, choices=[('bachelor', 'ตรี'), ('master', 'โท'), ('doctorate', 'เอก')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='grade_condition',
            field=models.CharField(blank=True, choices=[('all', 'ทั้งหมด'), ('from', 'ตั้งแต่')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='grade_from',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='grade_to',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='level',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'ตรี'), ('master', 'โท'), ('doctorate', 'เอก')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('primary', 'ประถม'), ('secondary', 'มัธยม'), ('vocational_minor', 'ปวช'), ('vocational_major', 'ปวส'), ('drop', 'เด็กซิ่ว'), ('degree', 'ปริญญา'), ('other', 'บุคคลทั่วไป')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
