# Generated by Django 4.2 on 2025-05-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_due_date_camp_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
