# Generated by Django 4.2 on 2025-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='degree_condition',
            new_name='degree_grade_condition',
        ),
        migrations.RenameField(
            model_name='camp',
            old_name='grade_condition',
            new_name='primary_grade_condition',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='camp_name',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='description_camp',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='grade_from',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='grade_to',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='level',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='num_candi',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='price',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='typeof_camp',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='camp',
            name='degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camp',
            name='drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camp',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camp',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camp',
            name='primary_grade_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='primary_grade_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='secondary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camp',
            name='secondary_grade_condition',
            field=models.CharField(blank=True, choices=[('all', 'ทั้งหมด'), ('from', 'ตั้งแต่')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='secondary_grade_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='secondary_grade_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='vocational_major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camp',
            name='vocational_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
