# Generated by Django 4.2 on 2025-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
