# Generated by Django 4.2 on 2025-05-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interest',
        ),
    ]
