# Generated by Django 4.2 on 2025-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_student_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='camp_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='description_camp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='final_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='num_candi',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='payment_type',
            field=models.CharField(choices=[('none', 'ไม่มีค่าใช้จ่าย'), ('pre', 'จ่ายตอนสมัคร'), ('post', 'จ่ายหลังประกาศรายชื่อ')], max_length=10, null=True, verbose_name='วิธีการชำระ'),
        ),
        migrations.AddField(
            model_name='camp',
            name='phone_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='typeof_camp',
            field=models.CharField(choices=[('health', 'ค่ายสายสุขภาพ'), ('engineer', 'ค่ายสายวิศวกรรม'), ('language', 'ค่ายสายภาษา'), ('architecture', 'ค่ายสายสถาปัตย์'), ('volunteer', 'ค่ายอาสา'), ('digital_it', 'ค่ายสายดิจิทัล/IT'), ('other', 'อื่นๆ')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='upload_file',
            field=models.FileField(null=True, upload_to='camp_uploads/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='detail_activity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='has_organized',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='linkcamp',
            field=models.URLField(null=True),
        ),
    ]
