# Generated by Django 4.2 on 2025-05-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_camp_camp_name_camp_description_camp_camp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
