# Generated by Django 4.2 on 2025-05-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_camp_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='has_organized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='organize_camp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
