# Generated by Django 4.2 on 2025-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_camp_has_organized_alter_camp_organize_camp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='has_organized',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
