# Generated by Django 4.2 on 2025-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
