# Generated by Django 4.2 on 2025-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_camp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
