# Generated by Django 4.2 on 2025-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_camp_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='linkcamp',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
